### ISSUE TITLE
Enable manage user accounts via admin console

### ISSUE THREAD

**Issue by samithaliyanage** [apache/airavata-custos#126]
we have a requirement to access user accounts via admin console. Currently it's possible via keycloak admin console. since you don't recommend to use keycloak interface, we are wondering whether this feature will be available via custos dashboard?

**Comment by smarru** [comment]
@samithaliyanage these capabilities exist in a portal developed to demonstrate custos capabilities - https://github.com/apache/airavata-custos-portal/tree/master/custos-demo-gateway an instance is deployed at https://testdrive.usecustos.org/ it is currently down but once it is up, you can give it a try. 

We are envisioning every tenant will be able to login to the admin portal and have a drop-down to see their tenant and administer the way you are asking.
