### ISSUE TITLE
Adding search capability to groups get all

### ISSUE THREAD

**Issue by dinukadesilva** [apache/airavata-custos#136]
Searching or filtering by group name or any other attributes.

**Comment by isururanawaka** [comment]
https://github.com/apache/airavata-custos/pull/140,
please validate

**Comment by dinukadesilva** [comment]
The searching group by name is working. Tested with client token. With the access token, the endpoint gives 400 with below response. 

```
{
 "code": 3,
 "message": "Error while validating method getAllGroups, value",
 "details": []
}
```

**Comment by isururanawaka** [comment]
@dinukadesilva please validate and close if the issue is resolved
