### ISSUE TITLE
Tenants GET endpoint has the status param set to "REQUESTED" by default

### ISSUE THREAD

**Issue by dinukadesilva** [apache/airavata-custos#141]
**Current Behavior**
The following request returns all the "REQUESTED" tenants.
`GET https://custos.scigap.org/apiserver/tenant-management/v1.0.0/tenants?limit=1000&offset=0`

**Expected Behavior**
This should return all of the tenants regardless of the status.

**Comment by isururanawaka** [comment]
https://github.com/apache/airavata-custos/pull/165

**Comment by isururanawaka** [comment]
reopen if issue exists
