### ISSUE TITLE
Append pagination meta data to tenants get all endpoint

### ISSUE THREAD

**Issue by dinukadesilva** [apache/airavata-custos#142]
Currently, the endpoint has `offset` and `limit` params that supports pagination. But, in order to visualize a pagination UI component, metadata (total rows or pages, etc.) about the pagination is required.

**Comment by isururanawaka** [comment]
merge with https://github.com/apache/airavata-custos/pull/146.

**Comment by dinukadesilva** [comment]
@isururanawaka 

Now, there's the `total_num_of_tenants` property on the response and the pagination can be shown accordingly. But, still, it has the status param set to "REQUESTED" so, cannot list all unless I make three requests for three statuses. Can we get rid of the default status and let the list be sorted according to the importance of statuses by default.

**Comment by dinukadesilva** [comment]
One other thing. I'm not sure if this was broken from recent changes. Pagination is not working. It returns the whole list. 

GET https://custos.scigap.org/apiserver/tenant-management/v1.0.0/tenants?limit=5&offset=0

Here, I'm expecting the response to be the first five tenants but actually, it returns a response of 45 "REQUESTED" tenants.

**Comment by dinukadesilva** [comment]
I just found that offset is not zero indexing and starting from 1 and then it returns the correct page size. Also, the last page seems not properly handled. if the last page is not complete (less than the limit), it returns a complete page of choice that doesn't make sense.

**Comment by dinukadesilva** [comment]
This is fixed
