### ISSUE TITLE
Is there any reason behind following snake case in JSON responses

### ISSUE THREAD

**Issue by dinukadesilva** [apache/airavata-custos#143]
I wonder why the API responses do not follow the camel case instead of the snake case in the JSON properties.

https://en.wikipedia.org/wiki/Naming_convention_(programming)

**Comment by isururanawaka** [comment]
Hi Dinuka, proto3 style guide suggests to write in snake case for field names. https://developers.google.com/protocol-buffers/docs/style. Anyway, json convention is done at envoy proxy so it converts those fields to snake case
