### ISSUE TITLE
Develop a Custos operator using K8 operator pattern

### ISSUE THREAD

**Issue by isururanawaka** [apache/airavata-custos#149]
- Examine existing helm charts
- Figure out the best strategy to develop Custos operators to deploy those microservices (Helm operator might help)
- Operators should be able to deploy Custos microservice, do rollouts ..etc
- Come up with Custom resource types for Custos in Kubernetes

**Comment by abhinav7sinha** [comment]
I am exploring the Custos Architecture at the moment regarding GSoC 2022. I was wondering what the status of this issue is?
I ask because I see a recent PR - https://github.com/apache/airavata-custos/pull/262 which looks like it accomplishes the items under this issue.

**Comment by isururanawaka** [comment]
@abhinav7sinha thanks for looking into it. the PR https://github.com/apache/airavata-custos/pull/262 is only for upgrading ingress version. But this is to develop a Custos Operator similar to https://github.com/keycloak/keycloak-operator to ease the process of deployment upgradees..etc. But I would like If you can look into way of backup existing Custos databases. Probably we can use https://velero.io/.

**Comment by abhinav7sinha** [comment]
@isururanawaka understood, I'll take a look into the Custos databases and understand how they can be backed up.
