### ISSUE TITLE
How to retrieve clientId and secret of a tenant after creation 

### ISSUE THREAD

**Issue by dinukadesilva** [apache/airavata-custos#154]
In the new UX designs, the client id and the secret are required to show even later in the system which means not just right after the creation. So, is there an endpoint to retrieve them separately or can those also be merged to the tenant objects?

POST https://custos.scigap.org/apiserver/tenant-management/v1.0.0/oauth2/tenant
{
 "client_id": "custos-ax354lwrwacyt5hahhiv-10001504",
 "client_secret": "ULjC6OKPk37rQ1FW4Bk1aitA9COVV3KNfL1Qd63o",
 "is_activated": true,
 "client_id_issued_at": 1618550500000,
 "client_secret_expires_at": 0,
 "registration_client_uri": "https://custos.scigap.org:32036/tenant-management/v1.0.0/oauth2/tenant?client_id=custos-ax354lwrwacyt5hahhiv-10001504",
 "token_endpoint_auth_method": "client_secret_basic",
 "msg": "Credentials are activated"
}

**Comment by isururanawaka** [comment]
Get https://custos.scigap.org/apiserver/identity-management/v1.0.0/credentials?client_id=client_id
Header: Bearer  encrypted_basic_token
