### ISSUE TITLE
The hierarchy of tenants

### ISSUE THREAD

**Issue by dinukadesilva** [apache/airavata-custos#155]
Hi @isururanawaka 

Is it correct to say there are only three levels for tenants as below

(1) super-tenant
(2) admin-tenant
(3) client-tenant

As of now, I can see that tenants who are in level (3) are not authorized to tenant endpoints. But, for end-users, the logo, tenant name (required), etc. are may be needed to show on the front-end application. Are there separate endpoints authorized and available? Also, those should be able to provide the tenant information by taking the client id (maybe as a parameter or through the token) since that's all the keys available in the frontend unless tenant ids also kept in the frontend config files.

Tenants who are in level (2) are authorized to tenant endpoints. (eg: create and manage tenants)

I doubt the existence and what's going on in the level (1). Are there any use-cases from that for the end-users? 

@dinukadesilva

**Comment by isururanawaka** [comment]
@dinukadesilva level 1 is the tenant of custos portal
