### ISSUE TITLE
Shouldn't all of the requests authorised by the access token

### ISSUE THREAD

**Issue by dinukadesilva** [apache/airavata-custos#158]
I can see some requests are authorized by the access token while some are not authorized at all and some are authorized by the base64 encoded clientId:secret. I wonder why

**Comment by isururanawaka** [comment]
Basically custos has three types of authorizations. User based authentication, agent based authentication and delegated authorization. For user and gent based authorizations we should use oAuth2.0 access tokens. For delegated access control we can use basic authentication.(e.g clients deployed on secured environments) But we can implement multiple authorizations schemes for a given endpoint. It is supported by MultitenantAuthInterceptor of Integration services. We need to extend that to the rest of the APIs if required.

**Comment by dinukadesilva** [comment]
But, the thing I'm doubtful about is, anyone is able to create an admin-tenant since it doesn't check for authentication or authorization at all. Does that make sense?

**Comment by isururanawaka** [comment]
@dinukadesilva  anyone can create admin tenants. but those are in the requested state. Custos admin manually approves those after verifying tenant details. It was an open API. But with custos admin portal, we can impose a restriction that all gateway requesters should be a user of the super tenant to request gateways. In that case we can authorize tenant creation apis.
