### ISSUE TITLE
Shouldn't the `search_criteria` be optional in `entities` endpoint

### ISSUE THREAD

**Issue by dinukadesilva** [apache/airavata-custos#200]
Currently, the search criteria is a mandatory parameter and the test driver custos portal makes separate requests for getting the list of different entity types. 

1. Need to have the `search_criteria` optional and return everything by default.
2. Have to have an identification of the entity type in the response objects. Currently, it's not.

**Comment by isururanawaka** [comment]
@dinukadesilva what you mean by identification?

**Comment by dinukadesilva** [comment]
I mean the entity type is not included in the entity object response.

**Comment by isururanawaka** [comment]
#204
