### ISSUE TITLE
JupyterHub Custos Authenticator: logout not working

### ISSUE THREAD

**Issue by zonca** [apache/airavata-custos#264]
* I login with Custos Authenticator using CILogon
* I try to logout both using the Logout button and https://jupyterhub/hub/logout
* Hub log shows `User logged out: `
* However, if I click again on the "Sign in with Custos Login", instead of getting to the login page, I am already logged in with my user account

@smarru @isururanawaka

**Comment by isururanawaka** [comment]
@zonca I will investigate this and let you know
