### ISSUE TITLE
JupyterHub Custos Authenticator: login with owner account

### ISSUE THREAD

**Issue by zonca** [apache/airavata-custos#265]
I have created the tenant with my XSEDE account
If I try to login with that same account, I get:

![image](https://user-images.githubusercontent.com/383090/163444143-6f0475d7-65ac-4031-95b3-25bcb9439fd7.png)

is this expected? am I supposed to never login with the account which owns the tenant?

**Comment by smarru** [comment]
@zonca Custos has a admin portal and a user portal, so if you are logging into tenant with the same account it should let you in. @isururanawaka thoughts on this scenario?

**Comment by isururanawaka** [comment]
@smarru @zonca  this happens when you try to login to the same account through a different identity provider than the one you used to create the account. In this is case you used login through XSEDE other than directly through institutional IDP or github account

**Comment by zonca** [comment]
not sure how that happened, my XSEDE account has my @sdsc email, while institutional has @ucsd.
I don't know how we can test it, now I have all the accounts in the system so cannot test this anymore.

**Comment by isururanawaka** [comment]
stale, please reopen if you see this again
