### ISSUE TITLE
Provide lightweight endpoint for user loading with minimal profile data

### ISSUE THREAD

**Issue by isururanawaka** [apache/airavata-custos#270]

**Comment by samithaliyanage** [comment]
In HTRC we like to have the following data in the minimal profile data.
- User's username
- User's First and Last names
- User's email
- User's attributes
- User's roles (This is not needed if there is a Custos API to retrieve users based on their roles. As described in (https://github.com/apache/airavata-custos/issues/276))

**Comment by isururanawaka** [comment]
https://github.com/apache/airavata-custos/pull/280

@samithaliyanage   please validate this. this can be used to load all users 
GET  https://custos.scigap.org/apiserver/user-management/v1.0.0/users/profile
parameters: offset, limit

**Comment by isururanawaka** [comment]
completed
