### ISSUE TITLE
Upgrade Dependencies

### ISSUE THREAD

**Issue by isururanawaka** [apache/airavata-custos#322]
Upgrade to upgrade to Apache Tomcat 9.0.68 
Upgrade to org.springframework:spring- beans@5.2.22.RELEASE or later
Upgrade to org.springframework.security:spring-security- crypto@5.5.7 or later
Upgrade to org.springframework:spring- core@5.2.22.RELEASE or later
 Upgrade to Keycloak 20.0.0 or later None 
Upgrade to org.dom4j:dom4j@2.1.3
Upgrade to io.netty:netty-transport@4.1.84
Upgrade to io.netty:netty-codec-http@4.1.84.Final

**Comment by abhinav7sinha** [comment]
Couple of action items - 
[ ] Upgrade dependencies across the project
[ ] Regression testing

**Comment by abhinav7sinha** [comment]
added protobuf java util dependency upgrade as well (it fixes the mac m1 build issue)

**Comment by abhinav7sinha** [comment]
for Spring upgrades:
- Upgrade to org.springframework:spring- [beans@5.2.22.RELEASE](mailto:beans@5.2.22.RELEASE) or later
  - dependency tree:

+- org.springframework.boot:spring-boot-starter-web:jar:2.2.0.RELEASE:compile
|  +- org.springframework:spring-web:jar:5.2.0.RELEASE:compile
|  |  \- org.springframework:spring-beans:jar:5.2.0.RELEASE:compile

+- org.springframework.boot:spring-boot-starter-actuator:jar:2.2.0.RELEASE:compile
|  +- org.springframework.boot:spring-boot-actuator-autoconfigure:jar:2.2.0.RELEASE:compile
|  |  +- org.springframework:spring-context:jar:5.2.0.RELEASE:compile
|  |  |  +- org.springframework:spring-beans:jar:5.2.0.RELEASE:compile

+- org.springframework.data:spring-data-jpa:jar:2.2.0.RELEASE:compile
|  +- org.springframework:spring-beans:jar:5.2.0.RELEASE:compile

+- io.springfox:springfox-swagger2:jar:2.9.2:compile
|  +- org.springframework.plugin:spring-plugin-core:jar:1.2.0.RELEASE:compile
|  |  +- org.springframework:spring-beans:jar:5.2.0.RELEASE:compile

|  \- org.springframework:spring-context:jar:5.2.0.RELEASE:compile
|     +- org.springframework:spring-beans:jar:5.2.0.RELEASE:compile

- Upgrade to org.springframework.security:spring-security- crypto@5.5.7 or later
- Upgrade to org.springframework:spring- [core@5.2.22.RELEASE](mailto:core@5.2.22.RELEASE) or later

**Comment by abhinav7sinha** [comment]
springfox doesn't seem to be maintained anymore, so we should migrate to springdoc.
https://springdoc.org/migrating-from-springfox.html

**Comment by abhinav7sinha** [comment]
[INFO] +- io.grpc:grpc-protobuf:jar:1.51.0:compile
[INFO] |  \- io.grpc:grpc-protobuf-lite:jar:1.51.0:compile
[INFO] +- io.grpc:grpc-netty:jar:1.51.0:compile
[INFO] |  +- io.grpc:grpc-core:jar:1.51.0:compile (version selected from constraint [1.51.0,1.51.0])
[INFO] |  |  +- com.google.code.gson:gson:jar:2.8.9:compile
[INFO] |  |  +- com.google.android:annotations:jar:4.1.1.4:runtime
[INFO] |  |  \- org.codehaus.mojo:animal-sniffer-annotations:jar:1.21:runtime
[INFO] |  +- io.netty:netty-codec-http2:jar:4.1.70.Final:compile
[INFO] |  |  +- io.netty:netty-common:jar:4.1.70.Final:compile
[INFO] |  |  +- io.netty:netty-buffer:jar:4.1.70.Final:compile
[INFO] |  |  +- io.netty:netty-transport:jar:4.1.70.Final:compile
[INFO] |  |  |  \- io.netty:netty-resolver:jar:4.1.70.Final:compile
[INFO] |  |  +- io.netty:netty-codec:jar:4.1.70.Final:compile
[INFO] |  |  +- io.netty:netty-handler:jar:4.1.70.Final:compile
[INFO] |  |  \- io.netty:netty-codec-http:jar:4.1.70.Final:compile

**Comment by abhinav7sinha** [comment]
The latest io.grpc maven project (v1.51.0) depends on  io.netty v4.1.70

**Comment by abhinav7sinha** [comment]
bumped to spring boot version 2.4.13 - it uses tomcat version 9.0.55. 
Figure out which version of spring boot uses 9.0.68
Incrementally upgrade spring boot to the version that uses tomcat v9.0.55.
