### ISSUE TITLE
Custom login page themes for user realms/applications

### ISSUE THREAD

**Issue by samithaliyanage** [apache/airavata-custos#69]
[NOTE]: # ( ^^ Provide a general summary of the request in the title above. ^^ )

## Is your feature request related to a problem? Please describe.
We want the ability to customize the look and feel of the Keycloak/Custos login page for our realms and applications. While this is possible with Keycloak, it is not possible yet with Custos.

## Describe the solution you'd like
Expose the Keycloak theming features through Custos APIs.

## Describe alternatives you've considered
N/A.

## Additional context
[TIP]:  # ( Why does this feature matter to you? What unique use cases do you have? )
Our app (HTRC Analytics Gateway) is designed to always redirect to an IDP for authentication  and now we need to support local accounts (for users who don't have institutional accounts). Our plan is to redirect to Custos for local account authentication and we would like to customize the look and feel of the login page.

**Comment by isururanawaka** [comment]
Completed and Tested
