### ISSUE TITLE
Error while using delete_tenant python API

### ISSUE THREAD

**Issue by virendrawali** [apache/airavata-custos#79]
## Description

Getting a **"Client ID should not be null"** error while trying to delete a client. Even though I just created the client using **create_admin_client** API
`def test_delete_tenant(tenant):
    response = client.delete_tenant(token, tenant.client_id)
    print(response)`

## Steps to Reproduce
```
def test_delete_tenant(tenant):
    response = client.delete_tenant(token, "custos-al6tf9r1aggetx6nrt1p-10000519")
```

## Error Message
rpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "Error occurred at deleteTenant UNKNOWN: Error while validating method deleteClient Client Id should not be null"
        debug_error_string = "{"created":"@1592589585.887821071","description":"Error received from peer ipv4:149.165.168.38:31499","file":"src/core/lib/surface/call.cc","file_line":1056,"grpc_message":"Error occurred at deleteTenant UNKNOWN: Error while validating method deleteClient Client Id should not be null","grpc_status":3}"

## Expected message 
message DeleteTenantRequest {
    string client_id = 1;
    int64 tenant_id = 2;
    Credentials credentials = 3;
    org.apache.custos.tenant.profile.service.Tenant body = 4;
}

**What is the difference between the tenant_id and the client_id??** In the response. after "create_admin_tenant" API is called only the client_id is returned.

**Comment by virendrawali** [comment]
@isururanawaka Could you please look into it?

**Comment by isururanawaka** [comment]
Activated the tenant. Check now

**Comment by virendrawali** [comment]
Thanks for your reply, Isuru. 
I did not know that the tenant has to be activated before it can be deleted. I will check how to activate the tenant and test again.

**Comment by virendrawali** [comment]
Hi Isuru,

I am able to delete a child tenant but the response returned by the API is empty and I was expecting status == True or something like that. Could you please check if we need to modify the deleteTenant response?  
    
Here is the code from the TenantManagementService.proto file. 
```
rpc deleteTenant (DeleteTenantRequest) returns (google.protobuf.Empty) {
        option (google.api.http) = {
           delete: "/tenant-management/v1.0.0/oauth2/tenant"
        };
    }
```

**Comment by virendrawali** [comment]
@isururanawaka , do above issue need to fix? I can work on this issue.
