### ISSUE TITLE
Error while calling update tenant API request

### ISSUE THREAD

**Issue by virendrawali** [apache/airavata-custos#81]
## Description
Getting error while executing the following code in update tenant. 

**"Error occurred at updateTenant INTERNAL: Error occurred during updateTenantjava.lang.RuntimeException: Error creating Realm in Keycloak Server, reason: HTTP 404 Not Found"**

```
client_id = "custos-msc8yfonps763adtp8za-10000425"
response = client.update_tenant(token, client_id,
                                        "Custos Portal",
                                        "irjanith@gmail.com", "Isuru", "Ranawaka", "irjanith@gmail.com", "isjarana",
                                        "Custos1234",
                                        self.contacts, self.redirect_uris, "https://custos.scigap.org/",
                                        "openid profile email org.cilogon.userinfo", "domain.org",
                                        "https://custos.scigap.org/", "Custos Portal")
```
## Steps to Reproduce
1. Create a new admin tenant
2, Execute get the tenant to verify that the tenant exists
3. Update the tenant with new data using the client ID returned in create_admin_tenant.
4. Update tenant API call will throw an error.

**Comment by isururanawaka** [comment]
you cannot update inactive tenant. All admin tenants are needed to activate by Custos admin. I have activated tenant custos-msc8yfonps763adtp8za-10000425 now. please check again

**Comment by virendrawali** [comment]
Is there a way to activate the tenant using the python sdk? So that I can do that within the test cases.

**Comment by isururanawaka** [comment]
> Is there a way to activate the tenant using the python sdk? So that I can do that within the test cases.

you can't activate admin tenants . It is granted only to the super credentials. What you can do is. first, create an admin tenant. Custos admin will approve it. then you can create child tenants of admin tenant by create_tenant method of TenantManagementClient. Please have look on Custos integration tests written in Java.

**Comment by virendrawali** [comment]
Sure, I will have a look. Will the custos admin have to manually approve the new admin tenant every time? In such a scenario, our test cases might fail very often in the future.

**Comment by isururanawaka** [comment]
> Sure, I will have a look. Will the custos admin have to manually approve the new admin tenant every time? In such a scenario, our test cases might fail very often in the future.

If you want to test tenant-related functions. go with child tenants. they will be automatically activated.
